# Generated by Django 3.0.4 on 2020-06-06 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tub_paths', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_size', models.FloatField(blank=True, null=True)),
                ('model_url', models.CharField(max_length=2000, null=True)),
                ('model_accuracy_url', models.CharField(max_length=2000, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
