# Generated by Django 3.0.4 on 2020-07-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='model_movie_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
